environment:
  matrix:
    - nodejs_version: 0.10
    # - nodejs_version: 0.11

platform:
  - x64
  - x86

install:
  - ps: Install-Product node $env:nodejs_version $env:Platform
  - ps: Start-FileDownload "http://mapbox.s3.amazonaws.com/windows-builds/visual-studio-runtimes/vcredist-VS2014-CTP4/vcredist_$env:Platform.exe"
  - .\vcredist_%platform%.exe /q /norestart
  - npm install
  - npm test

build: OFF
test: OFF
deploy: OFF

