environment:
  matrix:
#    - nodejs_version: 0.10
    - nodejs_version: 0.11

platform:
  - x86

matrix:
  allow_failures:
    - platform: x86
      nodejs_version: 0.10
    - platform: x86
      nodejs_version: 0.11

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
  - node --version
  - node -e "console.log(process.version)"
  - node -e "console.log(process.arch)"
  - npm --version
  - npm install
  - npm test

artifacts:
  - path: test
    name: TestOutputs

build: OFF
test: OFF
deploy: OFF
