language: node_js
node_js:
    - "6"
    - "8"

sudo: false

addons:
  apt:
    packages:
      - libgif-dev

notifications:
  irc:
    channels:
      - "irc.freenode.org#wikimedia-ri-ci"
    on_success: change
    on_failure: always
