_prefs: 
  saveCenter: true
_properties: 
  bridge: 
    "group-by": layer
attribution: Map data © OpenStreetMap contributors
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -120.21429061889626
  - 46.941121287752985
  - 13
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 22
minzoom: 0
mtime: 1395271871327
name: OSM Bright 2
scale: 1
source: "mapbox:///mapbox.mapbox-streets-v4"
styles: 
  - style.mss
  - road.mss
  - labels.mss
template: ''
