_prefs: 
  saveCenter: true
_properties: 
  bridge: 
    "group-by": layer
attribution: Map data © OpenStreetMap contributors
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - 7.31964111328125
  - 43.700395862593545
  - 12
description: ''
format: "png8:m=h"
interactivity_layer: ''
maxzoom: 22
minzoom: 0
mtime: 1387581515508
name: OSM Bright 2
scale: 1
source: "mapbox:///mapbox.mapbox-streets-v4"
styles: 
  - style.mss
  - road.mss
  - labels.mss
template: ''
