_prefs: 
  saveCenter: true
_properties: 
  bridge: 
    "group-by": layer
attribution: Map data © OpenStreetMap contributors
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -77.41241455078125
  - 39.42505541813694
  - 10
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 22
minzoom: 0
mtime: 1395269533315
name: OSM Bright 2
scale: 1
source: "mapbox:///mapbox.mapbox-streets-v4"
styles: 
  - style.mss
  - road.mss
  - labels.mss
template: ''
