_prefs: 
  saveCenter: true
_properties: 
  bridge: 
    "group-by": layer
attribution: Map data © OpenStreetMap contributors
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -77.04626083374023
  - 38.90051858534431
  - 13
description: ''
format: "png8:m=h"
interactivity_layer: ''
maxzoom: 22
minzoom: 0
mtime: 1374787736465
name: OSM Bright 2
scale: 1
source: "mapbox:///mapbox.mapbox-streets-v4"
styles: 
  - style.mss
  - road.mss
  - poi.mss
  - labels.mss
template: ''
